### ISSUE TITLE
Configurable WSDL path

### ISSUE THREAD

**Issue by RSully** [wsdl2phpgenerator/wsdl2phpgenerator#183]
Would it be feasible to add a config option that dictates the default WSDL URL written to the SoapClient implementation?

For most of my scripting I have a local WSDL I am using to generate classes, but I don't want my local computer's path written to the generated code - I would want to be able to specify something else, or at the very least, let it be null and force it to be given at runtime.

**Comment by kasperg** [comment]
Lets discuss a more generic solution to this in #197.
