### ISSUE TITLE
Operations with dashes in their signatures are not processed correctly

### ISSUE THREAD

**Issue by roninbar** [wsdl2phpgenerator/wsdl2phpgenerator#195]
Some web services (e.g. http://demo.toptix.com/demoweblink/2/get.resource/wsdl/SecurityService?target=java) use types with dashes in their names. Operations that use such types as input or output are skipped by the generator, e.g.

``` php
Connect-Response Connect(Connect-Request $ISecurityFacade_Connect_RequestMsg)
```

**Comment by kasperg** [comment]
You are absolutely right about the PHPDoc comments.
