### ISSUE TITLE
Error with baseType->getPhpIdentifier() === this->getPhpIdentifier()

### ISSUE THREAD

**Issue by pmarien** [wsdl2phpgenerator/wsdl2phpgenerator#211]
Fatal error: Maximum function nesting level of '500' reached, aborting! in ..../vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/ComplexType.php on line 241

Class: ComplexType

Method: protected function getBaseTypeMembers(ComplexType $type)

Problem: The baseType php_identifier is same like the current one. This force a Second Problem: The class would extend it self.

Solution: 
Method "setBaseType" should be changed from

   public function setBaseType(ComplexType $type)
    {
        $this->baseType = $type;
    }

to

   public function setBaseType(ComplexType $type)
    {
        if($type->getPhpIdentifier() !== $this->getPhpIdentifier())
        {
            $this->baseType = $type;
        }
    }

I will soon create a pull-request.

**Comment by pmarien** [comment]
version 3.1.2

**Comment by kasperg** [comment]
This seems to be a duplicate of #202.

**Comment by kasperg** [comment]
This is fixed in release 3.2.0.
