### ISSUE TITLE
PHP Fatal error:  Allowed memory size ComplexType.php

### ISSUE THREAD

**Issue by amusarra** [wsdl2phpgenerator/wsdl2phpgenerator#214]
Hi.
Using "Wsdl2PhpGenerator \ Generator()" to generate all classes get the error indicated in the subject. I tried to remove the limit on memory, this grows so incredible, see attached image and still have not able to get PHP classes.

Thanks for the support.
![schermata 2015-04-10 alle 21 00 05](https://cloud.githubusercontent.com/assets/708110/7095012/c3e309fe-dfc6-11e4-8931-7dc88d67df7f.png)

```
$generator = new \Wsdl2PhpGenerator\Generator();
$generator->generate(
    new \Wsdl2PhpGenerator\Config(array(
            'inputFile' => 'wsdl/JLegalArchive.wsdl',
            'outputDir' => 'ws/client/legalarchive/ifin/it',
            'soapClientOptions' => array(
                'authentication' => SOAP_AUTHENTICATION_BASIC,
                'login' => $configParams['JLegalArchiveService']['UserName'],
                'password' => $configParams['JLegalArchiveService']['Password'],
                'connection_timeout' => 60
            ))
    ));
```

**Comment by kasperg** [comment]
Have you been able to recreate this problem using a public WSDL or can you post the WSDL in question?

Without further information it could be an issue regarding infinite recursion caused by self-referencing types as discussed in #203 and #212.

**Comment by amusarra** [comment]
Hi.
You can find the WSDL document at this URL https://gist.github.com/amusarra/b76c9aa67dc166d0e9c5 
It is possible that there is the problem that you have indicated. As soon as I can I will make a new test.

Thx,
Antonio.

**Comment by kasperg** [comment]
Thank you for providing the WSDL. I just did a test run and the problem is as expected.

Please check out #203 for a solution to this.
