### ISSUE TITLE
OptionsResolver::setNormalizers() is deprecated

### ISSUE THREAD

**Issue by IdenGit** [wsdl2phpgenerator/wsdl2phpgenerator#215]
When i run generator they throw deprecated error. 

    PHP Deprecated:  The Symfony\Component\OptionsResolver\OptionsResolver::setNormalizers 
    method is deprecated since version 2.6 and will be removed in 3.0. Use setNormalizer() instead. 
    in /var/www/servers/php/sitename.dev/web/pkb/vendor/symfony/options-resolver
    /OptionsResolver.php on line 442

I fixed it manual - just comment exception string:

    public function setNormalizers(array $normalizers)
    {
        #trigger_error('The '.__METHOD__.' method is deprecated since version 2.6 and will be removed in 3.0. Use setNormalizer() instead.', E_USER_DEPRECATED); // i comment it

        foreach ($normalizers as $option => $normalizer) {
            $this->setNormalizer($option, $normalizer);
        }

        return $this;
    }  

that function used in Config.php class

    protected function configureOptions(OptionsResolverInterface $resolver)
    {
        ...
        $normalizers = array_map(function ($callable) {
            return function (Options $options, $value) use ($callable) {
                // Using reflection here is quite ugly. This can be reduced to the following once we drop 5.3 support.
                // return call_user_func_array($callable, func_get_args());
                list($object, $method) = $callable;
                $normalizer = new \ReflectionMethod(get_class($object), $method);
                $normalizer->setAccessible(true);
                return $normalizer->invokeArgs($object, func_get_args());
            };
        }, $normalizers);
        $resolver->setNormalizers($normalizers); //trouble is here
    }

You need use older version of symfony/options-resolver or re right your lib without deprecated functions.

**Comment by kasperg** [comment]
The library is perfectly functional with the OptionsResolver requirements specified in `composer.json`. The fact that versions from 2.6 decide to trigger an error should not change this.

As I see it the primary problem here is how your application handles `E_USER_DEPRECATED` errors. It should preferably be logged somewhere - not stop the evaluation of your code.

**Comment by IdenGit** [comment]
Thanks! I did it. But it isn't good solution as i think.

**Comment by kasperg** [comment]
#225 is a pull request for using the non-deprecated API.

**Comment by kasperg** [comment]
This is now part of release 3.2.1.
