### ISSUE TITLE
Naming scheme improvements

### ISSUE THREAD

**Issue by dkarlovi** [wsdl2phpgenerator/wsdl2phpgenerator#226]
Using v3.2.0 (from composer).

Looking at your naming scheme, you could improve the naming scheme, namely:
* you have `<method>Response`, why not have `<method>Request` as well
* you have class type as prefix (`ArrayOf`) and suffix (`Response`), why not go for suffixes everywhere, say `<type>Collection` instead of `ArrayOf`, that way your files are grouped, like ProductsCollection, ProductsRequest, ProductsResponse, etc.

Also, (this might not be common), I'm using an API which is using a Get prefix for its method names, so I end up with something like this in a Response (excuse the method names, those are localized, very consistent from the API provider):

    /**
     * @return ArrayOfTipKarteDto
     */
    public function getGetTipoviKarataResult()
    {
      return $this->GetTipoviKarataResult;
    }

    /**
     * @param ArrayOfTipKarteDto $GetTipoviKarataResult
     * @return \Cazmatrans\GetTipoviKarataResponse
     */
    public function setGetTipoviKarataResult($GetTipoviKarataResult)
    {
      $this->GetTipoviKarataResult = $GetTipoviKarataResult;
      return $this;
    }

**Comment by kasperg** [comment]
wsdl2phpgenerator provides very little in the form of a naming scheme.

Almost all naming is transferred directly from the source WSDL (with respect to PHP naming restrictions) including `<method>Response` and `ArrayOf`.

The only exceptions I can see for this is accessors which we prefix with [`get`](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/ComplexType.php#L148) and [`set`](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/ComplexType.php#L161). I agree that this is a bit unfortunate for your case but I see little reason to change it in general.

The code structure generated can be somewhat verbose and we have discussed ways to improve this (see #39). If you are interested in improving the situation I would be happy to look at a pull request.

**Comment by dkarlovi** [comment]
OK, I did not know that, I though most of the stuff was you naming things, just like the get/set thing.

Do you think a way to override/alias the stuff coming from the WSDL could work then? For example, for my above example I would say something like:

    [
        'GetTipoviKarata' => 'CardTypes', // translated back
    ]

which would in turn enable users to have a much more precise control over the tool's output (you get to make the API more in-line with your coding style without writing wrappers).

**Comment by kasperg** [comment]
Yes - that would be possible. 

Each type extracted from the WSDL contains [separate variables containing the WSDL name and PHP identifier](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/Type.php#L30-L38). Currently the only difference between these two values is to [ensure valid PHP class names](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/Type.php#L64-64).

You could add a configuration option which supported specifying class names by hand. The primary challenge here would be how to transfer the map from the configuration to the validation. We currently use a static validator. This is not very pretty and this change would probably require this to be refactored.

The map between PHP and WSDL type names is also used when calling the SOAP client in the form of the [`classmap` option](http://php.net/manual/en/soapclient.soapclient.php) so it should work for both code generation and service calls.

**Comment by dkarlovi** [comment]
I'd like to tackle this, I'm guessing the WIP pull request workflow is fine. Closing this, thanks.

**Comment by kasperg** [comment]
Great. I look forward to checking out the result.

WIP pull request is fine. Let me know if you need any input.
