### ISSUE TITLE
Old code?

### ISSUE THREAD

**Issue by red-led** [wsdl2phpgenerator/wsdl2phpgenerator#227]
[This method](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/Generator.php#L112-L129) has no actual uses.

**Comment by kasperg** [comment]
Could you elaborate?

The method is called [here](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/Generator.php#L109), which is again called [here](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/Generator.php#L86) and [here](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/Generator.php#L89).
