### ISSUE TITLE
Simple Types

### ISSUE THREAD

**Issue by kevinmlong** [wsdl2phpgenerator/wsdl2phpgenerator#242]
I'm curious how one should handle simple types in generating objects to pass to a SOAP web service. Let's say I have the following complex class:

```php
class BookReferenceType
{

  /**
   *
   * @var BookCodeType $code
   * @access public
   */
  public $code = null;

  /**
   *
   * @param BookCodeType $code
   * @access public
   */
  public function __construct($code)
  {
    $this->code = $code;
  }

}
```

The class BookCodeType is not created by the generator. It's essentially a string attribute as defined in the WSDL.  
```xml
<complexType name="SpecialBookReferenceType">
  <annotation>
    <documentation>A book identified by a identifier code</documentation>
  </annotation>
  <complexContent>
    <extension base="fb:BookReferenceType">
      <attribute name="code" type="ff:BookTypeCode" use="optional">
        <annotation>
          <documentation>Book's identifier code. e.g. "ZFGE"</documentation>
        </annotation>
      </attribute>
    </extension>
  </complexContent>
</complexType>
```
```xml
<simpleType name="BookCodeType">
  <annotation>
    <documentation>Book Code</documentation>
  </annotation>
  <restriction base="xs:string">
    <pattern value="[A-Z]{4}"/>
  </restriction>
</simpleType>
```
Passing "ZFGE" to `$book->code = "ZFGE";` throws an error as it's expecting it to be of type BookCodeType, which doesn't exist.

**NOTE:**    I've simplified this as I can't share the actual wsdl

Thoughts?

**Comment by jpastoor** [comment]
I have exactly the same problem.

Guess either the generated code should use a "string" type there or the BookCodeType should be generated as well?

Any solutions already made/found?

**Comment by mikaelcom** [comment]
Does this issue occur using https://github.com/WsdlToPhp/PackageGenerator? thks :smile:

**Comment by kevinmlong** [comment]
After further investigation, I guess it doesn't really matter the way that PHP handles types.
