### ISSUE TITLE
Unexpected class element type

### ISSUE THREAD

**Issue by minimihi** [wsdl2phpgenerator/wsdl2phpgenerator#249]
I think there might be a problem with class generation.
I'm expecting `MessageId` to be an array (of integers) and not mandatory. But in generated class it is integer and mandatory.

Generation script (using dev-master branch):
```php
$generator = new \Wsdl2PhpGenerator\Generator();
$generator->generate(
        new \Wsdl2PhpGenerator\Config(array(
            'inputFile' => __DIR__ . '/kis.wsdl',
            'outputDir' => __DIR__ . '/kis/',
            'soapClientClass' => '\BeSimple\SoapClient\SoapClient'
        ))
);
```

Part of definition:
```xml
<xs:complexType name="MarkMessagesAsReadRequestType">
	<xs:complexContent>
		<xs:extension base="ns1:RequestBaseType">
			<xs:sequence>
				<xs:element name="RequestData">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="MessageId" type="xs:long"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>
```
Generated class:
```php
class RequestData
{

    /**
     * @var int $MessageId
     */
    protected $MessageId = null;

    /**
     * @param int $MessageId
     */
    public function __construct($MessageId)
    {
      $this->MessageId = $MessageId;
    }

    /**
     * @return int
     */
    public function getMessageId()
    {
      return $this->MessageId;
    }

    /**
     * @param int $MessageId
     * @return RequestData
     */
    public function setMessageId($MessageId)
    {
      $this->MessageId = $MessageId;
      return $this;
    }

}
```

**Comment by mikaelcom** [comment]
Could you tell me if you encounter the same issue using [PackageGenerator](https://github.com/WsdlToPhp/PackageGenerator) ? :smile:

**Comment by kasperg** [comment]
Thanks for reporting this @minimihi. This is a known issue and #245 contains a fix for this.

The reason this has not be merged is that it breaks backwards compatibility. If we are to bump the major version I would prefer to bundle up more breaking changes.

Until then I would recommend that you pull in that fork/branch in your project.

**Comment by minimihi** [comment]
> Could you tell me if you encounter the same issue using PackageGenerator ?

From first glance it seems to be good :+1: 

> This is a known issue and #245 contains a fix for this.

Thanks @kasperg, it did the trick
