### ISSUE TITLE
question :: library to generate php classes

### ISSUE THREAD

**Issue by tonicospinelli** [wsdl2phpgenerator/wsdl2phpgenerator#258]
I made a library to generate PHP Classes (for the lulz) and I'm looking for this repo [class-generation](https://packagist.org/packages/tonicospinelli/class-generation) I think it will be very helpful. :wink: 

can you take a look? I you agree, I will make a PR with this changes :grin:

**Comment by red-led** [comment]
There is already pull request https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/pull/255 with ```Zend\Code\Generator```. See discussion in https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/issues/58.

**Comment by tonicospinelli** [comment]
@red-led great! I'll help with code review :wink:
