### ISSUE TITLE
Classmap also for generated Classes

### ISSUE THREAD

**Issue by garyee** [wsdl2phpgenerator/wsdl2phpgenerator#259]
Hi,

I am currently working on a Project where I had to generate a HTML-form based on a class in the WSDL.
I looked into generating the form from the XSD/WSDL but it was a major pain. So I ended up adding a $classMap attribute to the generated classes (just complexTypes).
So now I recursively go trough the class(attributes) which I want to represent in the form and generate HTML-elements by type (of the attributes).
Does anyone has an idea how to do it more ... elegantly?

**Comment by kasperg** [comment]
Why do you need a classmap for this? I would think you could use [reflection on the generated classes](http://php.net/manual/en/reflectionclass.getproperties.php) to achieve this.

**Comment by garyee** [comment]
yeah, thing is... the reflection-class will not return the type(or class) of the property.

**Comment by red-led** [comment]
@garyee, use (ReflectionProperty::getDocComment):[http://php.net/manual/en/reflectionproperty.getdoccomment.php] for this.

**Comment by garyee** [comment]
I have thought about it ... but it is not a very clean method and so I preferred to add the classmap property.

**Comment by mikaelcom** [comment]
@garyee What you aim to do is what has been done on https://www.wsdltophp.com using ReflectionClass on the generated classes (not generated with this project by the way) :wink:

**Comment by garyee** [comment]
@mikaelcom using the comments of the generated classes ?

**Comment by mikaelcom** [comment]
the comments you can see in any generated package at https://www.wsdltophp.com/Wsdls/79ab3ceaefaa5fa7d19bf8714074f0b7/Test-1-0-1-1-1-1-0-0-0-0 for example

**Comment by garyee** [comment]
@mikaelcom Sorry, but at this state of my project I won't switch to another generator lib :)
I wanted to know if you got get the types(classes) of the properties from the comments (using ReflectionProperty::getDocComment) or if there is a better way to do it.
@red-led using the comment-string is not a good way of doing it, more of a workaround... considering things like namespaces, format changes etc.

**Comment by kasperg** [comment]
@garyee: There are [many libraries which can parse DocBlocks](https://packagist.org/search/?q=docblock&orderBys%5B0%5D%5Bsort%5D=downloads&orderBys%5B0%5D%5Border%5D=desc) for you. They should be able to extract the type for you.

I consider that more clean compared to adding the classmap to all generated classes whichever way that is achieved

**Comment by garyee** [comment]
okay.

**Comment by garyee** [comment]
@kasperg: I looked at the libs in the link, but I thought ... why bring in an external library if all the stuff is already there. So I tried a something, which is more of a start ... 
[https://github.com/garyee/wsdl2phpgenerator/blob/DocBlocParser/lib/PhpSource/PhpDocComment.php](or a try) ...

**Comment by kasperg** [comment]
It does not make sense to expand the scope of our internal PhpSource library.

We are moving to Zend Code (See #255). [It also supports DocBlock reflection](https://github.com/zendframework/zend-code/blob/master/src/Reflection/DocBlockReflection.php).

**Comment by garyee** [comment]
okay nice, so I will wait for the update.
