### ISSUE TITLE
Parent should be added to the list of reserved keyword in Validator.php.

### ISSUE THREAD

**Issue by vtsao** [wsdl2phpgenerator/wsdl2phpgenerator#263]
https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/Validator.php#L38

Parent is a reserved keyword in PHP as well, even though it's not mentioned in the official PHP docs:
http://php.net/manual/en/reserved.keywords.php

You won't be able to name a class "Parent".

**Comment by kasperg** [comment]
Thanks for the input @vtsao. You are more than welcome to submit a pull request adding it.
