### ISSUE TITLE
Function isElementArray for maxOccurs fixed value

### ISSUE THREAD

**Issue by ginside** [wsdl2phpgenerator/wsdl2phpgenerator#276]
Having an element of this kind in the xml schema 
    <xs:complexType name="xxxxx">
        <xs:sequence>
            <xs:element name="yyyyy" minOccurs="0" maxOccurs="2" type="root:zzzz" />

Will generate a setter without an array as the parameter in the xxxx class
   /**
     * @param yyyyy
     */
    public function setYYYYY($yyyyy)

Instead of 
   /**
     * @param yyyyy[]
     */
    public function setYYYYY(array $yyyyy)

**Comment by kasperg** [comment]
Fixed in #272.
