### ISSUE TITLE
How to get type hinting for Laravel DI?

### ISSUE THREAD

**Issue by iherbivore** [wsdl2phpgenerator/wsdl2phpgenerator#283]
Currently I have to go through all of the generated files to add the complex type to parameters prior to the $parameterName. 

`public function __construct(SrchMsgRqHdr_CType $SrchMsgRqHdr,Ver_1_CType $Ver_1)`
instead of 
`public function __construct( $SrchMsgRqHdr, $Ver_1)`
 
 The comments already list the type for each parameter so I'm not sure why they aren't just included in the method signature. Am I overlooking a config option? Thanks!

**Comment by kasperg** [comment]
No you are not. There is no quick fix for this. The issue is discussed in #201.
