### ISSUE TITLE
Requesting files

### ISSUE THREAD

**Issue by Sajgoniarz** [wsdl2phpgenerator/wsdl2phpgenerator#288]
Hi!

I'm trying to create lib for Office365, but script required messages.xsd and types.xsd. When i delivered them i got an error :
`Fatal error occurred
Message: Uncaught exception 'SoapFault' with message 'SOAP-ERROR: Parsing WSDL: Couldn't bind to service' in \WSDL-Gen\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Xml\WsdlDocument.php:45
Stack trace:
#0 [internal function]: SoapClient->SoapClient('services.wsdl', Array)
#1 \WSDL-Gen\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Xml\WsdlDocument.php(45): ReflectionClass->newInstance('services.wsdl', Array)
#2 \WSDL-Gen\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Generator.php(104): Wsdl2PhpGenerator\Xml\WsdlDocument->__construct(Object(Wsdl2PhpGenerator\Config), 'services.wsdl')
#3 \WSDL-Gen\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Generator.php(89): Wsdl2PhpGenerator\Generator->load('services.wsdl')
#4 \WSDL-Gen\index.php(10): Wsdl2PhpGenerator\Generator->generate(Object(Wsdl2PhpGenerator\Config))
#5 {main}

Next exception 'Exception' with message 'Unable to load WSDL: SOAP-ERROR: Parsing WSD
`

**Comment by kasperg** [comment]
Apologies for the late reply. This issue is getting old.

If still relevant please reopen the issue and provide more information about the WSDL and XSDs you are trying to use - either as a link or by attaching them to this issue.
