### ISSUE TITLE
Php 7 array notation

### ISSUE THREAD

**Issue by thomasphansen** [wsdl2phpgenerator/wsdl2phpgenerator#293]
Hello, this is my first (plan on) contribution to wsdl2phpgenerator. All my projects are now running on PHP 7, and I would like wsdl2phpgenerator to create the arrays (when generating the soap calls) using the new notation style ( "['a' => 1]" , instead of "array('a' => 1)"). I'd like to add a new setting, a boolean called 'php7ArrayStyle'. This setting would be used to modify Service.php:204 and decide between the old notation style and the new one. This is actually the only place where wsdl2phpgenerator generates array output, AFAIK. What do you think? :D

**Comment by elpiel-efuture** [comment]
Maybe it will be a good idea to change the requirements for the package to >= 5.4 and use the short array syntax without any passed option. The maintenance of 5.6 is dropping this year, so it's a good idea to change the requirements of the package.

**Comment by thomasphansen** [comment]
I did a pull request to add support to bracket notation (you can get it on my fork, [here](https://github.com/thomasphansen/wsdl2phpgenerator)). I think wsdl2phpgenerator guys will prefer to keep it 100% compatible with 5.3, so that it can be useful for as much users as possible - but adding a setting for generating php 5.4+ compliant code would not break this premise, and that's why I think this to be a good aproach for this... ;)

**Comment by kasperg** [comment]
I agree with @elpiel-efuture here.

We are planning for a new release 4.0 anyway. I would include the change while bumping the PHP requirements.

Let's continue the discussion in #294.
