### ISSUE TITLE
fails with Uncaught exception 'InvalidArgumentException' with message 'Value() is null' 

### ISSUE THREAD

**Issue by skeagy** [wsdl2phpgenerator/wsdl2phpgenerator#297]
Follow-up to an issue closed without resolution. I have exactly the same problem with apparently the same source:
https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/issues/275

Here is my sample output:
`[error] [client 192.168.56.101] PHP Fatal error:  Uncaught InvalidArgumentException: Value() is null in /my/path/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Enum.php:95\nStack trace:\n
#0 /my/path/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(164): Wsdl2PhpGenerator\\Enum->addValue('')\n
#1 [internal function]: Wsdl2PhpGenerator\\Generator->Wsdl2PhpGenerator\\{closure}('', 1)\n
#2 /my/path/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(165): array_walk(Array, Object(Closure))\n
#3 /my/path/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(108): Wsdl2PhpGenerator\\Generator->loadTypes()\n
#4 /my/path/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(89): Wsdl2PhpGenerator\\Generator->load('../10.5/AXLAPI....')\n
#5 /my/path/convert.php(11): Wsdl2PhpGenerator\\Generator->generate(Object(Wsdl2PhpGenerator\\Config))\n
#6 {main}\n  thrown in /my/path/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Enum.php on line 95\n
`

Here is the script where I am invoking wsdl2phpgenerator:

convert.php:
`<?php
require('vendor/autoload.php');
ini_set('error_reporting', E_ALL);
$generator = new \Wsdl2PhpGenerator\Generator();
$generator->generate(
    new \Wsdl2PhpGenerator\Config(array(
        'inputFile' => '../10.5/AXLAPI.wsdl',
        'outputDir' => '/tmp/axl10.5_classes'
    ))
);
echo "done";
?>`

And attached are the wsdl and xsd files that it is trying to process.
[axl-wsdl-and-xsd.zip](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/files/551444/axl-wsdl-and-xsd.zip)

Thanks in advance for your help.

**Comment by kasperg** [comment]
Thanks for providing the WSDL and XSD. Let us continue this in #275.
