### ISSUE TITLE
Symfony2 intégration ?

### ISSUE THREAD

**Issue by ychoucha** [wsdl2phpgenerator/wsdl2phpgenerator#302]
Hello, 
 i mlooking a way to intégrate it on Symfony project, can u have some idea to how to do that

please ?

**Comment by kasperg** [comment]
This project generates framework agnostic code. I am not sure what you mean by Symfony integration.

You are welcome to elaborate but since a lot of time has passed this may no longer be relevant for you. I am closing for now.
