### ISSUE TITLE
ArrayOfint issues

### ISSUE THREAD

**Issue by Yuav** [wsdl2phpgenerator/wsdl2phpgenerator#311]
Expected class name: ArrayOfInt (uppercase I)
Actual class name: ArrayOfint

Expected constructor to take array (of int) as argument
Actual: Constructor takes no argument

**Comment by wizardist** [comment]
@Yuav you won't get `ArrayOf**I**nt` if you have `ArrayOf**i**nt` in your WSDL. All simple types are written in lower case, same for `ArrayOfstring`, `ArrayOfanyType`,

**Comment by Yuav** [comment]
Thanks for the clarification
