### ISSUE TITLE
how to set header

### ISSUE THREAD

**Issue by moeinrahimi** [wsdl2phpgenerator/wsdl2phpgenerator#316]
hi
right now i have this working:

// $xml = '
// <wsse:Security SOAP-ENV:mustUnderstand="1"><wsse:UsernameToken><wsse:Username>WSSD</wsse:Username>
// <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">p@ss4</wsse:Password>
// </wsse:UsernameToken></wsse:Security>
// ';
//         $header =  new Soapheader('s2',
//             'Security',new SoapVar($xml, XSD_ANYXML),true);

// // var_dump($header);
// $wsdl  = 'http://w5uat.isaaions.com/webservies/services/AAResWebServices?wsdl';

// $client = new SoapClient($wsdl,['trace'=>true,'exceptions'=>true]);            
// $client->__setSoapHeaders($header);

how can i add this to  the requests that i make with wsdl2phpgenerator  ?

**Comment by kasperg** [comment]
The project does not support setting headers at the moment.

Please see #269 for an alternate approach.
