### ISSUE TITLE
Looking for more collaborators

### ISSUE THREAD

**Issue by eberkund** [wsdl2phpgenerator/wsdl2phpgenerator#354]
There is a big backlog of nice looking pull requests, I think if the original authors no longer have time to work on this library it would be great if they could bring more people into the fold with privileges to accept PRs.

**Comment by eberkund** [comment]
@kasperg @walle @red-led @honzap

**Comment by kasperg** [comment]
Agreed.

I no longer do SOAP integrations at work. Combined with a general lack of time I have been neglecting this project.

If anyone is interested in helping out bringing the project forward including reviewing and merging PRs please let me know.

**Comment by mikaelcom** [comment]
Hi,

If you're looking for a project that is maintained and that will is evolving according to PHP versions, I would be pleased if you'd take a look to the [PackageGenerator](https://github.com/WsdlToPhp/PackageGenerator) project that is pretty similar to this one (from my point of view).
If you think the PackageGenerator project is missing features compared to this current project, feel free to create issues so we'll see if it can ease its usage and adoption.

Let me know anyway.

Good luck on this project.

**Comment by kasperg** [comment]
@gisostallenberg and @reyostallenberg has agreed to take over maintenance of wsdl2phpgenerator. Happy to have them on board.

**Comment by ivoba** [comment]
Nice! @kasperg @gisostallenberg @reyostallenberg 

Can you revoke my collaborator rights?
I actually just wanted to upgrade the wsdl2phpgenerator-cli package.
PR is still pending: https://github.com/wsdl2phpgenerator/wsdl2phpgenerator-cli/pull/8

**Comment by kasperg** [comment]
@ivoba Sure. I just removed you from the team.
