### ISSUE TITLE
URL override

### ISSUE THREAD

**Issue by alex-moreno** [wsdl2phpgenerator/wsdl2phpgenerator#363]
This may be a silly question, but how would you point to different urls, say for stage/qa/prod servers? I cannot see in the main generated class that there is any reference to that, only in the original wsdl.

Thanks in advance

**Comment by filippotoso** [comment]
Use the __setLocation() method on the service class (SoapClient sublass)

**Comment by gisostallenberg** [comment]
@alex-moreno I'm closing this as answered (or at least outdated)
