### ISSUE TITLE
question: incomplete Soap Request

### ISSUE THREAD

**Issue by nsn0x01** [wsdl2phpgenerator/wsdl2phpgenerator#369]
Hi,

I have other strange issue, wsdl2phpgenerator correctly generated the models.

Unfortunately when I send the request is incomplete...
If I set the object CityOrAirport, this is not sent in the request.
If I set only the Airport object is instead sent. 
The classmap is fine and contains all types, same calling __getType() on SoapClient.

This is the complexType, only setting minOccurs=1 on all elements then I got also the CityOrAirport object in XML request. 

**Is there other way for resolving?** 

	<xs:complexType name="typeSearchLocation">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Airport" minOccurs="0"/>
				<xs:element ref="City" minOccurs="0"/>
				<xs:element ref="CityOrAirport" minOccurs="0"/>
				<xs:element ref="CoordinateLocation" minOccurs="0"/>
				<xs:element ref="RailLocation" minOccurs="0"/>
			</xs:choice>
			<xs:element ref="Distance" minOccurs="0"/>
		</xs:sequence>

/**
 * This class stands for typeSearchLocation StructType
 * @subpackage Structs
 */
class TypeSearchLocation extends AbstractStructBase
{
    /**
     * The Airport
     * Meta informations extracted from the WSDL
     * - minOccurs: 0
     * - ref: Airport
     * @var \TestClient\Services\Air\StructType\Airport
     */
    public $Airport;
    /**
     * The City
     * Meta informations extracted from the WSDL
     * - minOccurs: 0
     * - ref: City
     * @var \TestClient\Services\Air\StructType\City
     */
    public $City;
    /**
     * The CityOrAirport
     * Meta informations extracted from the WSDL
     * - minOccurs: 0
     * - ref: CityOrAirport
     * @var \TestClient\Services\Air\StructType\CityOrAirport
     */
    public $CityOrAirport;
    /**
     * The CoordinateLocation
     * Meta informations extracted from the WSDL
     * - minOccurs: 0
     * - ref: CoordinateLocation
     * @var \TestClient\Services\Air\StructType\CoordinateLocation
     */
    public $CoordinateLocation;
    /**
     * The RailLocation
     * Meta informations extracted from the WSDL
     * - minOccurs: 0
     * - ref: RailLocation
     * @var \TestClient\Services\Air\StructType\RailLocation
     */
    public $RailLocation;
    /**
     * The Distance
     * Meta informations extracted from the WSDL
     * - minOccurs: 0
     * - ref: Distance
     * @var \TestClient\Services\Air\StructType\Distance
     */
    public $Distance;

....
}

**Comment by mikaelcom** [comment]
Hi @nsn0x01, I think you want to create this issue at https://github.com/WsdlToPhp/PackageGenerator/issues as it seems to me that the generated code is from the https://github.com/WsdlToPhp/PackageGenerator project. Am I wrong?

**Comment by techork** [comment]
try to replace
<xsd:choice>
with
<xsd:choice minOccurs="0" maxOccurs="unbounded">

**Comment by gisostallenberg** [comment]
@nsn0x01 I'm closing this as invalid
