### ISSUE TITLE
wrong generated class for same model name

### ISSUE THREAD

**Issue by nsn0x01** [wsdl2phpgenerator/wsdl2phpgenerator#370]
in the same .xsd file there are two FlightType

<xs:element name="Modifier1">
			<xs:attribute name="FlightType" use="optional" default="Direct">
				<xs:annotation>
					<xs:documentation>Type of flights to be returned. Values are 'NonStop', 'Direct', 'SingleConnection' and 'NoRestrictions'. Available in AirExchangeMultiQuoteReq only.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Direct"/>
						<xs:enumeration value="NonStop"/>
						<xs:enumeration value="SingleConnection"/>
						<xs:enumeration value="NoRestrictions"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
</xs:element>

<xs:element name="Modifier2">
    <xs:element ref="FlightType" minOccurs="0"/>
</xs:element>

	<xs:element name="FlightType">
		<xs:annotation>
			<xs:documentation>Modifier to request flight type options example non-stop only, non-stop and direct only, 
                include single online connection etc.
        </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="RequireSingleCarrier" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="MaxConnections" use="optional" default="-1">
				<xs:annotation>
					<xs:documentation>The maximum number of connections within a
                        segment group.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:annotation>
							<xs:documentation>To support other provider like 1P maxConnection values ranged from -1 to 3. Here -1 means user don't know about connection information. 
                                     In case of maxConnection -1, maxStop value will be considered.   
                               </xs:documentation>
						</xs:annotation>
						<xs:minInclusive value="-1"/>
						<xs:maxInclusive value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="MaxStops" use="optional" default="-1">
				<xs:annotation>
					<xs:documentation>The maximum number of stops within a
                        connection.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:annotation>
							<xs:documentation>To support other provider like 1P maxStop values ranged from -1 to 3. Here -1 means provider can ignore the maxStop value.</xs:documentation>
						</xs:annotation>
						<xs:minInclusive value="-1"/>
						<xs:maxInclusive value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="NonStopDirects" type="xs:boolean" use="optional"/>
			<xs:attribute name="StopDirects" type="xs:boolean" use="optional"/>
			<xs:attribute name="SingleOnlineCon" type="xs:boolean" use="optional"/>
			<xs:attribute name="DoubleOnlineCon" type="xs:boolean" use="optional"/>
			<xs:attribute name="TripleOnlineCon" type="xs:boolean" use="optional"/>
			<xs:attribute name="SingleInterlineCon" type="xs:boolean" use="optional"/>
			<xs:attribute name="DoubleInterlineCon" type="xs:boolean" use="optional"/>
			<xs:attribute name="TripleInterlineCon" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>

GENERATED CLASS for Modifier2:

    /**
     * Set FlightType value
     * @uses \TestClient\Services\Air\EnumType\FlightType::valueIsValid()
     * @uses \TestClient\Services\Air\EnumType\FlightType::getValidValues()
     * @throws \InvalidArgumentException
     * @param string $flightType
     * @return \TestClient\Services\Air\StructType\AirSearchModifiers
     */
    public function setFlightType($flightType = null)
    {
        // validation for constraint: enumeration
        if (!\TestClient\Services\Air\EnumType\FlightType::valueIsValid($flightType)) {
            throw new \InvalidArgumentException(sprintf('Value "%s" is invalid, please use one of: %s', $flightType, implode(', ', \TestClient\Services\Air\EnumType\FlightType::getValidValues())), __LINE__);
        }
        $this->FlightType = $flightType;
        return $this;
    }

Unfortunately the validation is not valid for Modifier2 but only for Modifier1. 
The signature should be different for class Modifier2 accepting the object FlightType, while for class Modifier1 is fine the previous generated code.

Removing the validation works but it's a workaround.

Could you please have a look at this?

**Comment by mikaelcom** [comment]
hi @nsn0x01, I think you want to create this issue at the https://github.com/WsdlToPhp/PackageGenerator/issues as this generated code seems to have been generated from the https://github.com/WsdlToPhp/PackageGenerator project. Am I wrong?

**Comment by nsn0x01** [comment]
yes sorry
