### ISSUE TITLE
$implements is not initialized

### ISSUE THREAD

**Issue by Sauerbrei** [wsdl2phpgenerator/wsdl2phpgenerator#381]
Recently, we have upgraded to PHP7.3 and since then there might be an issue with uninitialized instance variables such as `$implements` when checking its `count()`. I run into this error on a docker container:

```
php_1          | In PhpClass.php line 156:
php_1          |
php_1          |   [Symfony\Component\Debug\Exception\ContextErrorException]
php_1          |   Warning: count(): Parameter must be an array or an object that implements C
php_1          |   ountable
```

It could be fixed on line 51 with a simple

`private $implements = [];`

or in the constructor on line 116:

`$this->implements = array();`

Any other suggestions?

**Comment by gisostallenberg** [comment]
See #386 and #378
