### ISSUE TITLE
Replace code generation code with external library

### ISSUE THREAD

**Issue by kasperg** [wsdl2phpgenerator/wsdl2phpgenerator#58]
I think we should consider replacing [our custom php generation code](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/tree/master/lib/Wsdl2PhpGenerator/PhpSource) with an external library.

In line with replacing CLI code with Symfony Console (#) This would allow us to build on a well established code base and focus on the primary task of of the project: The actual conversion of WSDLs to PHP code.

I have considered two libraries:
- https://github.com/schmittjoh/cg-library
- https://github.com/zendframework/Component_ZendCode

I am currently leaning towards using ZendCode. 

Pros:
- Somewhat documented ([example](http://mwop.net/blog/261-Code-Generation-with-ZendCodeGenerator.html))
- [Improved support for DocBlocks](https://github.com/zendframework/Component_ZendCode/blob/master/Generator/DocBlockGenerator.php)

Cons:
- Long dependency chain
- Small user base

I would love to hear opinions from others.

**Comment by sagikazarmark** [comment]
I suggest using an AST builder library. Nowadays I'm using one by @Ocramius:

https://github.com/Ocramius/CodeGenerationUtils

**Comment by Ocramius** [comment]
@sagikazarmark depends on what you need:
 - transformation on code => AST (libs similar to mine)
 - simple code generation => templating (pretty much Zend\Code)

**Comment by sagikazarmark** [comment]
I haven't done too much code generation, so I am not sure. But I think using twig for something like this is not really a good idea.

**Comment by Ocramius** [comment]
> twig for something like this is not really a good idea

No, twig is not a good idea. I'm talking about Zend\Code\Generator here. Templating is not just strings :P

**Comment by sagikazarmark** [comment]
I took a look at Zend Code. :+1:

**Comment by mikaelcom** [comment]
I've made my own library after all without having taking time to look to another existing library.
You can see it here: https://github.com/WsdlToPhp/PhpGenerator

**Comment by kasperg** [comment]
@red-led has started working on this in #255 using Zend Code. Let us continue the discussion there. I am closing this.
