### ISSUE TITLE
Non-static method DOMDocument::load() should not be called statically

### ISSUE THREAD

**Issue by s001dxp** [wsdl2phpgenerator/wsdl2phpgenerator#9]
I ran the following command:

php wsdl2php.php -i c:\wsdl\metaswitch\definition\ShServiceTyped.wsdl -o /files

The following error was produced:

Strict Standards: Non-static method DOMDocument::load() should not be called statically, assuming $this from incompatible context in /wsdl2php/src/Generator.php on line 140

Suggested change:

replace line 140:
    $this->dom = DOMDocument::load($wsdl);

with the following:
    $this->dom = new DOMDocument;
    $this->dom->load($wsdl);

**Comment by noranoranoranora** [comment]
Strict Standards: Non-static method DOMDocument::load() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\myhome\components\com_sobipro\lib\cms\joomla_common\base\lang.php on line 144

who know how to solve it?
